# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'A  lot of Subscribers'},
        ),
    ]
